/**
 * English gallery chrome copy, constrained by `GalleryStrings` to the shape of the Chinese
 * dictionary in strings.ts. Catalog titles and descriptions come from catalog.ts itself.
 */
import type { GalleryStrings } from "./strings";

export const en: GalleryStrings = {
  brand: {
    title: "Penguin UI",
    subtitle: "Component gallery",
  },
  rail: {
    theme: "Theme",
    mode: "Mode",
    size: "Size",
    language: "Language",
    langNames: { en: "EN", zh: "中文" },
    modes: { light: "Light", dark: "Dark", system: "System" },
    sizeTitle: (px) => `${px}px root`,
    compare: "Compare themes",
    reducedMotion: "Reduced motion",
    fonts: "Fonts & licences",
    sections: "Sections",
    feedbackTitle: "Feedback",
    feedbackBody: "Quote the breadcrumb under a card, or copy its address with the link button.",
  },
  intro: {
    title: "Component gallery",
    body: "The shared UI package's tokens, component demos and screen composites, switchable across three themes, light and dark, three sizes and two languages. Every section and variant has a stable address: quote the breadcrumb or copy the link.",
    summary: (sections, demos, planned) =>
      `${sections} sections · ${demos} with demos · ${planned} planned`,
    coverage: "Token coverage",
    coverageHint:
      "Tokens defined per theme × mode; an undefined token reads “unset” on every page.",
    missingList: "Undefined tokens",
    resolving: "Resolving tokens…",
    problems: "Demo problems",
  },
  section: {
    copyLink: "Copy link",
    copied: "Copied",
    copyBreadcrumb: "Copy breadcrumb",
    tokens: "Tokens",
    code: "Code",
    tokensIn: (where) => `Resolved in ${where}`,
    noTokens: "This demo declares no tokensUsed.",
    generatedFrom: (file) => `Generated from tokens.ts by ${file}.`,
    unset: "unset",
    loadingCode: "Loading source…",
    compareFrame: (theme) => `${theme} preview`,
  },
  planned: {
    badge: "Planned",
    wave: "Wave",
    exports: "Exports",
    props: "Props",
    replaces: "Replaces",
    plans: { move: "Move", new: "New", lift: "Lift", "move-new": "Move + extend" },
  },
  screens: {
    open: "Open full screen",
    missing: (id) =>
      `No composition yet; add "${id}" to SCREENS in packages/ui/src/screens/index.ts and it appears here.`,
    back: "Back to the gallery",
    notFound: (name) => `There is no screen named “${name}”.`,
    title: "Screens",
  },
  uncatalogued: {
    title: "Uncatalogued demos",
    description: "These demos' ids are not in catalog.ts.",
  },
  foundations: {
    view: { active: "Active theme", matrix: "All themes" },
    contrastAgainst: "Contrast",
    presets: "Accent presets",
    presetsHint: "A preset overrides the theme's own accent in every theme and both modes.",
    families: "Families",
    roleScale: "Role scale",
    weights: "Weights",
    tracking: "Tracking",
    radiusScale: "Radius",
    borderWidths: "Border widths",
    onControls: "On control shapes",
    shadows: "Shadow levels",
    glass: "Glass",
    controls: "Control heights",
    measured: "measured",
    rows: "Rows and menu rows",
    padding: "Card and panel padding",
    stack: "Stack gaps",
    durations: "Durations × easings",
    liveSignal: "Live signal",
    reducedNote: "Reduced motion: animations hold their first frame.",
    iconSizes: "Icon sizes",
    iconStroke: "Stroke",
    iconRegistry: (icons, files) => `${icons} icons from ${files} files`,
    duplicateNames: "One path, several names",
    focusRing: "Focus ring",
    inputFocus: "Input focus",
    selection: "Selection",
    scrollbar: "Scrollbar",
    layers: "Tiers",
    layerRows: [
      ["none", "Page content and the sidebar"],
      ["z-40", "In-flow menus"],
      ["z-50", "Modal and drawer backdrops"],
      ["z-[60]", "Portaled panels: dropdowns, popovers, context menus"],
      ["z-[65] / z-[70]", "The dock's drag ghost"],
      ["z-[100]", "Toasts"],
    ],
    sampleButton: "Button",
    sampleInput: "Input",
    sampleCard: "Card",
    sampleBadge: "Badge",
    sampleMenuRow: "Menu row",
    sampleRow: "List row",
  },
  fonts: {
    title: "Fonts & licences",
    specimens: "Specimens",
    specimensHint: "Each theme's families, one en and one zh paragraph at 16 / 18 / 20 px.",
    declared: "Declared faces",
    declaredHint:
      "The @font-face rules in the page's stylesheets; a browser downloads one only when text uses it.",
    noFaces: "No faces declared yet (W0b adds the fonts).",
    slices: (n) => `${n} slices`,
    licences: "Licence texts",
    noLicences: "No licence texts yet (W0b adds packages/ui/src/fonts/LICENSES/).",
    status: { loaded: "loaded", unloaded: "unused", loading: "loading", error: "failed" },
  },
  catalog: {
    groups: {},
    sections: {},
    tokenGroups: {},
  },
};
