/**
 * Gallery chrome copy (bilingual): this file holds the Chinese dictionary `zh` and the
 * `GalleryStrings` shape; the English dictionary lives in strings-en.ts. These strings are the
 * gallery's own and never reach the product. Theme names (Primer / Frost / Console), component
 * names, token names and breadcrumbs stay English in both.
 *
 * `catalog` translates catalog.ts titles and descriptions. English reads catalog.ts directly, so
 * only `zh` fills it; a test checks it covers every group and section.
 */
import type { TokenGroupId } from "@prismshadow/penguin-ui";

export const zh = {
  brand: {
    title: "Penguin UI",
    subtitle: "组件画廊",
  },
  rail: {
    theme: "主题",
    mode: "明暗",
    size: "字号",
    language: "语言",
    langNames: { en: "EN", zh: "中文" },
    modes: { light: "浅色", dark: "深色", system: "跟随系统" },
    sizeTitle: (px: number) => `根字号 ${px}px`,
    compare: "三主题并排",
    reducedMotion: "减弱动效",
    fonts: "字体与许可",
    sections: "目录",
    feedbackTitle: "反馈",
    feedbackBody: "引用卡片下方的路径，或用标题行的链接按钮复制地址。",
  },
  intro: {
    title: "组件画廊",
    body: "共享 UI 包的基础令牌、组件演示与整页合成，可在三套主题、明暗、三档字号与中英文之间切换。每个分区与变体都有稳定地址：反馈时引用路径或链接即可。",
    summary: (sections: number, demos: number, planned: number) =>
      `${sections} 个分区 · ${demos} 个已有演示 · ${planned} 个计划中`,
    coverage: "令牌覆盖",
    coverageHint: "每个主题 × 明暗已定义的令牌数；未定义的令牌在各页显示为「未定义」。",
    missingList: "未定义的令牌",
    resolving: "正在解析令牌…",
    problems: "演示问题",
  },
  section: {
    copyLink: "复制链接",
    copied: "已复制",
    copyBreadcrumb: "复制路径",
    tokens: "令牌",
    code: "代码",
    tokensIn: (where: string) => `${where} 下的取值`,
    noTokens: "该演示未声明 tokensUsed。",
    generatedFrom: (file: string) => `由 ${file} 根据 tokens.ts 生成。`,
    unset: "未定义",
    loadingCode: "正在加载源码…",
    compareFrame: (theme: string) => `${theme} 预览`,
  },
  planned: {
    badge: "计划中",
    wave: "波次",
    exports: "导出",
    props: "属性",
    replaces: "替代",
    plans: { move: "迁移", new: "新建", lift: "提取", "move-new": "迁移并扩展" },
  },
  screens: {
    open: "打开整页",
    missing: (id: string) =>
      `尚无合成：在 packages/ui/src/screens/index.ts 的 SCREENS 中加入「${id}」即可出现。`,
    back: "返回画廊",
    notFound: (name: string) => `没有名为「${name}」的整页。`,
    title: "整页合成",
  },
  uncatalogued: {
    title: "未编入目录的演示",
    description: "这些演示的 id 不在 catalog.ts 中。",
  },
  foundations: {
    view: { active: "当前主题", matrix: "全部主题" },
    contrastAgainst: "对比度",
    presets: "强调色预设",
    presetsHint: "预设在每个主题、两种明暗下都覆盖主题自带的强调色。",
    families: "字体族",
    roleScale: "角色字号",
    weights: "字重",
    tracking: "字距",
    radiusScale: "圆角",
    borderWidths: "描边宽度",
    onControls: "用在控件上",
    shadows: "阴影层级",
    glass: "毛玻璃",
    controls: "控件高度",
    measured: "实测",
    rows: "行与菜单行",
    padding: "卡片与面板内边距",
    stack: "堆叠间距",
    durations: "时长 × 缓动",
    liveSignal: "实时信号",
    reducedNote: "已减弱动效：动画停在首帧。",
    iconSizes: "图标尺寸",
    iconStroke: "描边",
    iconRegistry: (icons: number, files: number) => `${icons} 个图标，来自 ${files} 个文件`,
    duplicateNames: "同一路径的多个名字",
    focusRing: "焦点环",
    inputFocus: "输入框焦点",
    selection: "选区",
    scrollbar: "滚动条",
    layers: "层级",
    layerRows: [
      ["无", "页面内容与侧栏"],
      ["z-40", "页内菜单"],
      ["z-50", "模态框与抽屉的遮罩"],
      ["z-[60]", "门户面板：下拉、弹出层、右键菜单"],
      ["z-[65] / z-[70]", "停靠面板拖拽中的幽灵"],
      ["z-[100]", "通知"],
    ] as readonly (readonly [string, string])[],
    sampleButton: "按钮",
    sampleInput: "输入框",
    sampleCard: "卡片",
    sampleBadge: "徽标",
    sampleMenuRow: "菜单行",
    sampleRow: "列表行",
  },
  fonts: {
    title: "字体与许可",
    specimens: "字样",
    specimensHint: "每个主题的字体族，在 16 / 18 / 20 px 下各排一段中英文。",
    declared: "已声明的字体",
    declaredHint: "页面样式表中的 @font-face；只有文本用到时浏览器才会下载。",
    noFaces: "尚未声明任何字体（字体由 W0b 加入）。",
    slices: (n: number) => `${n} 个分片`,
    licences: "许可文本",
    noLicences: "还没有许可文本（W0b 会加入 packages/ui/src/fonts/LICENSES/）。",
    status: { loaded: "已加载", unloaded: "未使用", loading: "加载中", error: "失败" },
  },
  catalog: {
    groups: {
      foundations: {
        title: "基础",
        description: "令牌契约的可视化：每个令牌，在每个主题与明暗下。",
      },
      icons: { title: "图标与标记", description: "线形图标、状态标记、加载环、头像与标识。W1。" },
      actions: { title: "操作", description: "按钮、链接、复制与快捷键提示。W1。" },
      forms: { title: "表单", description: "字段、文本控件、选择器、开关与设置行。W2。" },
      navigation: {
        title: "导航",
        description: "标签页、导航行、分组、路径、图标栏与命令面板。W4、W7、W8。",
      },
      overlays: { title: "浮层", description: "对话框、抽屉、菜单、弹出层、提示与通知。W3。" },
      feedback: {
        title: "反馈与状态",
        description: "徽标、计数、提示条、骨架、空状态与进度。W1、W4。",
      },
      layout: { title: "布局与表面", description: "卡片、页面框架、分区、行与拖拽手柄。W4、W7。" },
      data: {
        title: "数据展示",
        description: "表格、键值列表、统计、日志、图例、环形图与迷你折线。W4、W8。",
      },
      content: { title: "内容", description: "Markdown、代码、排版原语与差异视图。W5。" },
      chat: { title: "对话", description: "气泡、流式文本、工具调用、审批与输入框。W6。" },
      files: { title: "文件与目录树", description: "文件树、文件浏览器、预览与拖放遮罩。W7。" },
      shell: { title: "外壳与停靠", description: "应用外壳、侧栏、停靠面板、启动球与工具栏。W7。" },
      charts: {
        title: "图表与仪表",
        description: "领域图表留在 Web 中，读取 --ui-chart-* 令牌。W8。",
      },
      screens: { title: "整页", description: "只用包内组件与模拟数据拼成的整页合成。" },
    } as Partial<Record<string, { title: string; description: string }>>,
    sections: {
      "foundations-color": {
        title: "颜色",
        description: "表面、文字、线条、强调色、六种语义色调、图表与代码。",
      },
      "foundations-typography": {
        title: "排版",
        description: "字体族、h1–h6 到说明文字的角色字号、字重与字距。",
      },
      "foundations-radius": { title: "形状", description: "控件形状上的圆角梯度，以及描边宽度。" },
      "foundations-elevation": {
        title: "层次与毛玻璃",
        description: "五级阴影，以及铺在渐变底上的毛玻璃配方。",
      },
      "foundations-density": {
        title: "间距与密度",
        description: "实测高度的控件档位、行与菜单行内边距、堆叠间距。",
      },
      "foundations-motion": { title: "动效", description: "时长、缓动曲线与实时信号的节奏。" },
      "foundations-icons": {
        title: "图标",
        description: "Web App 的线形图标，按主题的描边粗细、端点与转角绘制。",
      },
      "foundations-focus": { title: "焦点与选区", description: "焦点环、选区颜色与滚动条。" },
      "foundations-hooks": {
        title: "样式钩子",
        description: "封闭的钩子列表，每个钩子挂在其配方所需的最小结构上。",
      },
      "foundations-layering": { title: "层级", description: "所有浮层从中取值的堆叠层级。" },
      "icons-glyph-icon": { description: "唯一的线形图标渲染器，描边读取 --ui-icon-stroke。" },
      "icons-registry": { title: "图标表", description: "所有路径字符串，按组归档，只声明一次。" },
      "icons-marks": { title: "标记", description: "与线形图标并存的非网格标记。" },
      "icons-dot": { description: "6/8/10 px 的状态圆点，可脉动（Console 为闪烁）。" },
      "icons-spinner": { description: "三种尺寸、取色调墨色的加载环。" },
      "icons-status-icon": { description: "运行状态图标，基于 Spinner。" },
      "icons-activity-icon": { description: "会话行上的沙漏、挤压与未读标记。" },
      "icons-avatars": { title: "头像", description: "身份方块，单个与堆叠。" },
      "icons-logos": { title: "标识", description: "品牌标识。" },
      "icons-update-dot": { description: "更新轨迹标记（不是语义色调）。" },
      "actions-button": { description: "按钮：五种变体、五种尺寸、加载中。" },
      "actions-icon-button": { description: '必须带 label 的 size="icon" 按钮。' },
      "actions-button-class": { description: "把按钮外观套到 <label> 上。" },
      "actions-link": { description: "行内与独立链接，外链带图标。" },
      "actions-copy-button": { description: "复制后切换为对勾，并播报给读屏。" },
      "actions-close-button": { description: "扁平的 ×。" },
      "actions-kbd": { description: "键盘快捷键提示。" },
      "actions-hidden-file-input": { description: "读屏可见的隐藏文件输入及其包含块。" },
      "actions-create-buttons": { description: "AI 创建与手动创建按钮对。" },
      "forms-field": { description: "标签、提示与错误的骨架，两种布局。" },
      "forms-input": { description: "文本控件，支持框内前后缀。" },
      "forms-select": { description: "控件外观的选择器。" },
      "forms-picker-list": { description: "带搜索、可键盘遍历的列表。" },
      "forms-checkbox": { description: "基于原生控件，支持半选态。" },
      "forms-radio": { description: "基于 fieldset 的单选组。" },
      "forms-switch": { description: "开关。" },
      "forms-toggle-row": { description: "标签（带「?」）与提示，旁边一个开关。" },
      "forms-segmented": { description: "分段控件，带徽标位。" },
      "forms-search-input": { description: "带清除按钮的搜索框。" },
      "forms-swatch-picker": { description: "圆形色板，使用 aria-pressed。" },
      "forms-pref-row": { description: "设置行与带分隔线的操作行。" },
      "forms-tag-input": { description: "可逐个移除的标签行。" },
      "navigation-tabs": { description: "下划线标签页。" },
      "navigation-nav-list": { description: "侧栏与导航行：图标、文字、徽标；选中与禁用态。" },
      "navigation-group-header": { description: "可折叠分组与分页。" },
      "navigation-breadcrumbs": { description: "路径面包屑，中段可折叠为 …。" },
      "navigation-rail": { description: "48 px 图标栏，带提示。" },
      "navigation-dock-tabs": { description: "带关闭按钮的胶囊标签。" },
      "navigation-command-palette": { description: "⌘K：搜索、分组结果与快捷键提示。" },
      "overlays-modal": { description: "对话框；sm 以下变为底部抽屉。" },
      "overlays-confirm-modal": { description: "无标题栏的确认卡片。" },
      "overlays-paged-dialog": { description: "带页面导航栏的对话框。" },
      "overlays-drawer": { description: "侧边面板与弹簧底部抽屉。" },
      "overlays-floating-panel": {
        description: "菜单、弹出层与提示共用的外壳（Frost 为毛玻璃）。",
      },
      "overlays-menu": { description: "一套菜单行，两种密度。" },
      "overlays-dropdown": { description: "锚定面板，支持键盘遍历。" },
      "overlays-portal-panel": { description: "定位与关闭逻辑；三种打开方式。" },
      "overlays-info-popover": { description: "「?」弹出层与帮助折叠。" },
      "overlays-tooltip": { description: "提示。" },
      "overlays-lightbox": { description: "可缩放的图片。" },
      "overlays-toaster": { description: "顶部通知，取语义色调令牌。" },
      "feedback-badge": { description: "色调胶囊：浅底、描边或实心。" },
      "feedback-count": { description: "数字计数胶囊。" },
      "feedback-notice": { description: "统一的提示条 / 标注：色调，可选标题、操作、关闭与重试。" },
      "feedback-todo-notice": { description: "页面待办，基于 Notice。" },
      "feedback-skeleton": { description: "加载占位。" },
      "feedback-empty-state": { description: "空状态，可带虚线框。" },
      "feedback-progress-bar": { description: "确定或不确定进度，带色调阈值。" },
      "feedback-duration-slot": { description: "运行中实时计时，结束后定格为耗时。" },
      "feedback-beta-badge": { description: "上标标签。" },
      "layout-card": { description: "带边框的表面；Frost 大圆角，Console 描边。" },
      "layout-page-frame": { description: "页面滚动容器、宽度上限、带「?」的 h1 与工具栏。" },
      "layout-ruled-section": { description: "细线分区：左侧标题，右侧操作、计数与「?」。" },
      "layout-collapsible-section": { description: "标题栏下方可折叠的内容区。" },
      "layout-disclosure-row": { description: "吸顶的单行展开行。" },
      "layout-list-row": { description: "前置方块、标题、元信息与尾部操作。" },
      "layout-entity-header": { description: "标识或方块、名称、id、胶囊与链接。" },
      "layout-resize-handle": { description: "信息色调的拖拽条。" },
      "data-table": { description: "统一的表格：带底色或朴素表头、密度、悬停、可展开行。" },
      "data-key-value": { description: "以网格或行排列的 <dl>。" },
      "data-stat-tile": { description: "图标、标签、带色调的数值与详情；方块或条带。" },
      "data-stat-chip": { description: "图标加等宽数值。" },
      "data-log-view": { description: "等宽 <pre> 框，可带头部与尾部。" },
      "data-legend": { description: "图例列表，三种色块形状。" },
      "data-ring": { description: "分段环形仪表，带阈值。" },
      "data-sparkline": { description: "折线，可带面积。" },
      "data-chart-frame": { description: "坐标轴、网格与悬停框架。" },
      "content-prose": { description: "带应用插件的 react-markdown 与 .md-body 样式。" },
      "content-code-block": { description: "带语言标签与复制的 Shiki 双主题代码面。" },
      "content-typography": { title: "标题与文本", description: "读取角色令牌的排版原语。" },
      "content-diff-viewer": { description: "统一或并排差异，Shiki 高亮、块头与词级高亮。" },
      "content-workspace-file-editor": { description: "CodeSurface 叠加 textarea 的编辑器。" },
      "chat-message-bubble": { description: "用户、图片与插话气泡，悬停显示元信息。" },
      "chat-assistant-text": {
        description: "定稿的正文，或带光标的流式文本（Console 为步进的块状光标）。",
      },
      "chat-work-group": { description: "包裹步骤的折叠卡片。" },
      "chat-tool-call-card": {
        description: "工具行：状态、名称、副标题、耗时、审批、参数与输出。",
      },
      "chat-approval": { description: "允许 / 拒绝按钮对，与提醒色调的载荷面。" },
      "chat-subagent-chip": { description: "头像、名称、id，以及加载环或圆点。" },
      "chat-task-stats-line": { description: "每轮末尾的统计小片。" },
      "chat-changes-card": { description: "「N 个文件 / N 条记忆更新」，可展开更多。" },
      "chat-context-ring": { description: "14 px 的上下文环，80% / 95% 阈值。" },
      "chat-composer": {
        title: "输入框",
        description: "输入框外壳、标签行、工具栏触发器、发送 / 停止与斜杠列表。",
      },
      "chat-model-select": { description: "模型选择器，胶囊与表单两种形态。" },
      "chat-menu-select": { description: "审批、思考、Skill 与 Agent 选择器背后的图标行选择。" },
      "chat-channel-bubble": { description: "公司群聊气泡。" },
      "files-file-tree": { description: "Workspace 文件树。" },
      "files-file-browser": { description: "文件树与预览并排。" },
      "files-tree-pane": { description: "带搜索、刷新与上传头部的文件树。" },
      "files-preview-pane": { description: "图片、PDF、Markdown、源码与不支持类型的预览。" },
      "files-drop-overlay": { description: "拖放目标遮罩。" },
      "files-workspace-file-menu": { description: "文件右键菜单行。" },
      "shell-app-shell": { description: "图标栏、侧栏、横幅、主区、停靠面板与抽屉的插槽。" },
      "shell-sidebar": { description: "侧栏框架与展示型会话行。" },
      "shell-dock-frame": { description: "头部拖柄、DockTabs、操作、内容与拖拽手柄。" },
      "shell-dock-picker": { description: "停靠面板的面板选择器。" },
      "shell-launcher": { description: "悬浮启动球与展开扇面（带弹簧）。" },
      "shell-panels-toolbar": { description: "双开关的面板工具栏。" },
      "shell-mobile-top-bar": { description: "移动端顶栏。" },
      "shell-terminal-appearance": { description: "从实时令牌生成 xterm 主题与字体。" },
      "charts-domain": {
        title: "领域图表",
        description:
          "图表、日历、看板与组织画布留在 Web 中，构建在 ChartFrame、Legend、Ring、Sparkline 与 ProgressBar 之上。",
      },
      "screens-chat": {
        title: "对话",
        description: "侧栏与对话：运行中的工具调用、思考块、定稿回答与输入框。",
      },
      "screens-traces": { title: "Trace", description: "带时间线泳道的 Trace 面板。" },
      "screens-settings": { title: "设置", description: "打开在「外观」页的分页设置对话框。" },
      "screens-login": { title: "登录", description: "登录页。" },
    } as Partial<Record<string, { title?: string; description: string }>>,
    tokenGroups: {
      "color-surfaces": "颜色 — 表面",
      "color-text": "颜色 — 文字",
      "color-lines": "颜色 — 线条",
      "color-accent": "颜色 — 强调色",
      "color-tones": "颜色 — 语义色调",
      "color-charts": "颜色 — 图表",
      "color-code": "颜色 — 代码",
      shape: "形状",
      elevation: "层次",
      "type-families": "排版 — 字体族",
      "type-scale": "排版 — 字号与角色",
      density: "密度",
      motion: "动效",
      icons: "图标",
      focus: "焦点、选区与滚动条",
    } as Partial<Record<TokenGroupId, string>>,
  },
};

export type GalleryStrings = typeof zh;
