/**
 * The gallery's table of contents: groups → sections, in the order the gallery renders them.
 *
 * One section per row of the component partition (A-architecture §3). A `component` section is
 * rendered by the demo whose `id` equals the section id (`components/<group>/<name>/<name>.demo.tsx`)
 * and, until that demo exists, by a placeholder built from the planned fields below — so the
 * gallery shows the whole plan from day one and fills in wave by wave. A `foundation` section is a
 * page the gallery generates from `tokens.ts`; a `screen` section links a full-viewport composite
 * under `/screens/<name>`.
 *
 * Ids are stable addresses: `#<id>` anchors, `/embed?demo=<id>`, screenshot file names and quoted
 * feedback all use them. Rename one only together with everything that links it.
 *
 * Plain data with erasable types only, so Node can import this file directly
 * (`packages/ui-gallery/scripts/shots.mjs` does).
 */

/** How a planned component gets into the package (A-architecture §3). */
export type CatalogKind = "move" | "new" | "lift" | "move-new";

/** The migration wave a section lands in (A-architecture §7). */
export type CatalogWave = "W0" | "W1" | "W2" | "W3" | "W4" | "W5" | "W6" | "W7" | "W8";

export interface FoundationSection {
  kind: "foundation";
  id: string;
  title: string;
  description: string;
}

export interface ComponentSection {
  kind: "component";
  id: string;
  /** The section title — the component's name, or the family's for a multi-export row. */
  title: string;
  /** Every export the row plans, in the order the partition lists them. */
  components: readonly string[];
  /** One line: what the component is for. */
  description: string;
  /** The planned props, as the partition spells them. */
  props: string;
  /** The web code it replaces, as the partition cites it. Empty for a component with no predecessor. */
  replaces: string;
  plan: CatalogKind;
  wave: CatalogWave;
}

export interface ScreenSection {
  kind: "screen";
  id: string;
  /** The `/screens/<name>` route segment. */
  screen: string;
  title: string;
  description: string;
}

export type CatalogSection = FoundationSection | ComponentSection | ScreenSection;

export interface CatalogGroup {
  id: string;
  title: string;
  description: string;
  sections: readonly CatalogSection[];
}

const c = (
  id: string,
  title: string,
  components: readonly string[],
  description: string,
  props: string,
  replaces: string,
  plan: CatalogKind,
  wave: CatalogWave,
): ComponentSection => ({
  kind: "component",
  id,
  title,
  components,
  description,
  props,
  replaces,
  plan,
  wave,
});

export const CATALOG: readonly CatalogGroup[] = [
  {
    id: "foundations",
    title: "Foundations",
    description: "The token contract rendered: every name, in every theme and mode.",
    sections: [
      {
        kind: "foundation",
        id: "foundations-color",
        title: "Colour",
        description: "Surfaces, text, lines, accent, the six tones, charts and code.",
      },
      {
        kind: "foundation",
        id: "foundations-typography",
        title: "Typography",
        description: "Families, the role scale h1–h6 to caption, weights and tracking.",
      },
      {
        kind: "foundation",
        id: "foundations-radius",
        title: "Shape",
        description: "The radius scale on control shapes, and the border widths.",
      },
      {
        kind: "foundation",
        id: "foundations-elevation",
        title: "Elevation & glass",
        description: "Five shadow levels and the glass recipe over a wash.",
      },
      {
        kind: "foundation",
        id: "foundations-density",
        title: "Spacing & density",
        description: "Control rungs with measured heights, row and menu padding, stack gaps.",
      },
      {
        kind: "foundation",
        id: "foundations-motion",
        title: "Motion",
        description: "Durations, easings and the live-signal timing.",
      },
      {
        kind: "foundation",
        id: "foundations-icons",
        title: "Icons",
        description: "The Web App's line icons drawn at the theme's stroke, cap and join.",
      },
      {
        kind: "foundation",
        id: "foundations-focus",
        title: "Focus & selection",
        description: "Focus rings, the selection colour and the scrollbar.",
      },
      {
        kind: "foundation",
        id: "foundations-hooks",
        title: "Style hooks",
        description: "The closed hook list, each on the markup its recipes expect.",
      },
      {
        kind: "foundation",
        id: "foundations-layering",
        title: "Layering",
        description: "The stacking tiers every overlay picks from.",
      },
    ],
  },
  {
    id: "icons",
    title: "Icons & Marks",
    description: "Line icons, state marks, spinners, avatars and logos. Wave W1.",
    sections: [
      c(
        "icons-glyph-icon",
        "GlyphIcon",
        ["GlyphIcon"],
        "The one line-icon renderer; stroke from --ui-icon-stroke.",
        "d, size?: IconSize, filled?",
        "glyph-icon.tsx; group-list.tsx Icon",
        "move",
        "W1",
      ),
      c(
        "icons-registry",
        "Icon registry",
        ["icons.ts"],
        "Every path string, grouped, declared once.",
        "ICONS.plus, ICONS.trash, …",
        "icons.tsx paths, stat-icons.ts, group-list.tsx, session-row-menu.tsx, company-nav-icons.ts; the 9 redeclared plus, 5 trash, pencil/eye/key/rotate/back copies",
        "move",
        "W1",
      ),
      c(
        "icons-marks",
        "Marks",
        [
          "Chevron",
          "ChevronDown",
          "CheckIcon",
          "CloseIcon",
          "PlusIcon",
          "DownloadIcon",
          "UploadIcon",
        ],
        "The off-grid marks kept beside the line icons.",
        "as today",
        "chevron.tsx, icons.tsx",
        "move",
        "W1",
      ),
      c(
        "icons-dot",
        "Dot",
        ["Dot"],
        "A 6/8/10 px state dot with an optional pulse (Console: blink).",
        'tone, size?: "xs" | "sm" | "md", pulse?, label?',
        "≈20 hand dots (dock-panel.tsx:170, update-row.tsx:39, OrgStatusDot, ToneCount, ChartStateDot, …)",
        "new",
        "W1",
      ),
      c(
        "icons-spinner",
        "Spinner",
        ["Spinner"],
        "A ring at three sizes in tone ink.",
        'size?: "xs" | "sm" | "md", tone?, label',
        "13 copies (update-row.tsx:35, models-page.tsx:1879/…, subagent-chip.tsx:66, …)",
        "new",
        "W1",
      ),
      c(
        "icons-status-icon",
        "StatusIcon",
        ["StatusIcon"],
        "The run-state glyph, built on Spinner.",
        "as today",
        "status-icon.tsx",
        "move",
        "W1",
      ),
      c(
        "icons-activity-icon",
        "ActivityIcon",
        ["ActivityIcon", "BackgroundTasksMark", "ScheduleMark"],
        "Hourglass, squeeze and unread marks on a session row.",
        "activity, size, labels",
        "session-activity-icon.tsx",
        "move",
        "W1",
      ),
      c(
        "icons-avatars",
        "Avatars",
        ["AgentAvatar", "UserAvatar", "AvatarStack"],
        "Identity tiles, alone and stacked.",
        "id/name/src, size; items, max, size",
        "agent-avatar.tsx, user-avatar.tsx; stacks in channel-header.tsx:68, benchmark-page.tsx:93; initial discs ×3",
        "move-new",
        "W1",
      ),
      c(
        "icons-logos",
        "Logos",
        ["ProviderLogo", "PenguinLogo"],
        "Brand marks.",
        "as today; src prop",
        "provider-logo.tsx, penguin-logo.tsx",
        "move",
        "W1",
      ),
      c(
        "icons-update-dot",
        "UpdateDot",
        ["UpdateDot"],
        "Update trail marks (not a tone).",
        "as today",
        "update-dot.tsx",
        "move",
        "W1",
      ),
    ],
  },
  {
    id: "actions",
    title: "Actions",
    description: "Buttons, links, copy and keyboard hints. Wave W1.",
    sections: [
      c(
        "actions-button",
        "Button",
        ["Button"],
        "The button: five variants, five sizes, loading.",
        'variant: "primary" | "secondary" | "danger" | "ghost" | "link"; size: "xs" | "sm" | "md" | "icon" | "icon-sm"; loading?; leading?: ReactNode',
        "button.tsx; ≈40 square icon buttons (headerControlClass, iconActionClass, …); 13 tiny outline buttons; 12 brand link-buttons",
        "move-new",
        "W1",
      ),
      c(
        "actions-icon-button",
        "IconButton",
        ["IconButton"],
        'Button size="icon" that requires a label.',
        'label, glyph: string, size?: "sm" | "md", variant?',
        "the same square icon-button cluster",
        "new",
        "W1",
      ),
      c(
        "actions-button-class",
        "buttonClass()",
        ["buttonClass"],
        "The Button look on a <label>.",
        "(variant, size)",
        "labelButtonClass; trace-import-row.tsx:159, models-page.tsx:3000",
        "move",
        "W1",
      ),
      c(
        "actions-link",
        "Link",
        ["Link"],
        "In-text and standalone links with an external glyph.",
        'href, external?, variant?: "inline" | "standalone"',
        "ExternalLink, ReleasesLink, models-page.tsx anchors, MdLink colour",
        "new",
        "W1",
      ),
      c(
        "actions-copy-button",
        "CopyButton",
        ["CopyButton", "useCopied", "CopiedStatus"],
        "Copy with a check swap and a live region.",
        "text, label, size?",
        "copy-button.tsx",
        "move",
        "W1",
      ),
      c(
        "actions-close-button",
        "CloseButton",
        ["CloseButton"],
        "The flat ×.",
        "onClose, label?",
        "icons.tsx:143",
        "move",
        "W1",
      ),
      c(
        "actions-kbd",
        "Kbd",
        ["Kbd"],
        "A keyboard hint.",
        "keys: string[]",
        "dock picker kbd, terminal hints",
        "new",
        "W1",
      ),
      c(
        "actions-hidden-file-input",
        "HiddenFileInput",
        ["HiddenFileInput"],
        "An sr-only file input with its containing block.",
        "as today",
        "hidden-file-input.tsx",
        "move",
        "W1",
      ),
      c(
        "actions-create-buttons",
        "CreateButtons",
        ["CreateButtons"],
        "The AI / manual create pair.",
        "as today (labels required)",
        "create-buttons.tsx",
        "move",
        "W4",
      ),
    ],
  },
  {
    id: "forms",
    title: "Forms",
    description: "Fields, text controls, pickers, toggles and settings rows. Wave W2.",
    sections: [
      c(
        "forms-field",
        "Field",
        ["Field", "FieldLabel", "FieldHint", "FieldError", "RequiredMark"],
        "The label / hint / error scaffold in two layouts.",
        "as today",
        "field.tsx; 17 raw red error paragraphs → FieldError",
        "move",
        "W2",
      ),
      c(
        "forms-input",
        "Input",
        ["Input", "Textarea", "PasswordInput"],
        "Text controls with in-field affixes.",
        'size: "sm" | "base", mono, affix?: {leading?, trailing?}',
        "input.tsx, password-input.tsx; in-field affixes (useAffixWidth, id prefix)",
        "move-new",
        "W2",
      ),
      c(
        "forms-select",
        "Select",
        ["Select", "OptionMenu", "FormPicker"],
        "Pickers on the control look.",
        "as today",
        "select.tsx, option-menu.tsx, form-picker.tsx; ProtocolSuffixMenu becomes an OptionMenu",
        "move",
        "W2",
      ),
      c(
        "forms-picker-list",
        "PickerList",
        ["PickerList"],
        "A search box over a keyboard-walkable list.",
        "generic <T> as today",
        "model-select.tsx:63; machines host picker",
        "move",
        "W2",
      ),
      c(
        "forms-checkbox",
        "Checkbox",
        ["Checkbox"],
        "Native-backed, with an indeterminate state.",
        "checked, indeterminate?, label?, hint?, size?",
        "models-page.tsx:3115, messaging-binding-editor.tsx:585, schedule-form-modal.tsx:483, StoredSecretRow",
        "new",
        "W2",
      ),
      c(
        "forms-radio",
        "Radio",
        ["Radio", "RadioGroup"],
        "A fieldset-backed radio group.",
        "options[{value,label,hint?}], value, onChange, orientation",
        "memory-tab.tsx:922",
        "new",
        "W2",
      ),
      c(
        "forms-switch",
        "Switch",
        ["Switch"],
        "The on/off switch.",
        "as today",
        "switch.tsx",
        "move",
        "W2",
      ),
      c(
        "forms-toggle-row",
        "ToggleRow",
        ["ToggleRow"],
        'A label (with its "?") and hint beside a Switch.',
        "label, hint?, info?, checked, onChange, disabled?",
        "6 spellings (PrefRow + Switch, boxed toggle card ×2, bare rows ×4, DeliveryOptionRow)",
        "new",
        "W2",
      ),
      c(
        "forms-segmented",
        "Segmented",
        ["Segmented"],
        "A segmented control with a badge slot.",
        "as today",
        "segmented.tsx; 6 hand toggles (workspace-browser.tsx:1963, SteerModeRow, …)",
        "move",
        "W2",
      ),
      c(
        "forms-search-input",
        "SearchInput",
        ["SearchInput"],
        "A search box with a clear button.",
        "size, value, onChange, placeholder, clearLabel",
        "menuSearchClass, panelSearchClass, sidebar.tsx:2059, Input type=search",
        "new",
        "W2",
      ),
      c(
        "forms-swatch-picker",
        "SwatchPicker",
        ["SwatchPicker"],
        "Round swatches with aria-pressed.",
        "options[{value,color,label}], value, onChange",
        "AccentPicker",
        "move",
        "W2",
      ),
      c(
        "forms-pref-row",
        "PrefRow",
        ["PrefRow", "SettingsSection"],
        "Settings rows and the ruled action row.",
        "as today",
        "setting-row.tsx, section-shell.tsx, project-dialogs.tsx SettingRow",
        "move",
        "W2",
      ),
      c(
        "forms-tag-input",
        "TagInput",
        ["TagInput"],
        "A chip row with remove buttons.",
        "chips[{key,label,glyph?,removable}], onRemove, trailing?",
        "the composer chip row",
        "new",
        "W6",
      ),
    ],
  },
  {
    id: "navigation",
    title: "Navigation",
    description:
      "Tabs, nav rows, groups, crumbs, the rail and the command palette. Waves W4, W7, W8.",
    sections: [
      c(
        "navigation-tabs",
        "Tabs",
        ["Tabs"],
        "Underline tabs.",
        "as today",
        "tabs.tsx",
        "move",
        "W4",
      ),
      c(
        "navigation-nav-list",
        "NavList",
        ["NavList", "NavRow"],
        "Sidebar and nav rows: glyph, label, badge; active and disabled.",
        "items[{key,label,glyph,badge?,disabled?}], active, onSelect, density",
        "the rail/nav row family ×8 (sidebar.tsx:1877/…, paged-dialog.tsx:42, project-dialogs.tsx:285, dock-panel.tsx:249)",
        "new",
        "W4",
      ),
      c(
        "navigation-group-header",
        "GroupHeader",
        ["GroupHeader", "FolderSection", "MoreRow", "Pager"],
        "Collapsible groups and paging.",
        "as today (labels via props)",
        "group-list.tsx; errors-panel.tsx:405 PagerButton",
        "move",
        "W4",
      ),
      c(
        "navigation-breadcrumbs",
        "Breadcrumbs",
        ["Breadcrumbs"],
        "Path crumbs with a middle … collapse.",
        'items[{label,onClick?}], collapse?: "middle"',
        "workspace-browser.tsx:2460",
        "new",
        "W7",
      ),
      c(
        "navigation-rail",
        "Rail",
        ["Rail"],
        "The 48 px icon rail with tooltips.",
        "items[], active, footer",
        "app-layout.tsx:70 CollapsedRail; rail squares ×8",
        "lift",
        "W7",
      ),
      c(
        "navigation-dock-tabs",
        "DockTabs",
        ["DockTabs", "DockTabButton"],
        "Pill tabs with a close button.",
        "tabs[{key,label,glyph,badge?}], active, onSelect, onClose",
        "dock-panel.tsx:131",
        "lift",
        "W7",
      ),
      c(
        "navigation-command-palette",
        "CommandPalette",
        ["CommandPalette"],
        "⌘K: search, grouped results and keyboard hints.",
        "open, onClose, groups[{label, items[{key,label,hint?,glyph?,onRun}]}], placeholder, emptyText, recent?",
        "",
        "new",
        "W8",
      ),
    ],
  },
  {
    id: "overlays",
    title: "Overlays",
    description: "Dialogs, drawers, menus, popovers, tooltips and toasts. Wave W3.",
    sections: [
      c(
        "overlays-modal",
        "Modal",
        ["Modal", "pushEscLayer", "popEscLayer", "FOCUSABLE_SELECTOR"],
        "The dialog; a sheet below sm.",
        'as today, size: "sm" … "6xl" replaces widthClass',
        "modal.tsx",
        "move",
        "W3",
      ),
      c(
        "overlays-confirm-modal",
        "ConfirmModal",
        ["ConfirmModal", "useSaveConfirm"],
        "The headerless confirm card.",
        "as today (labels via UiStrings defaults, overridable)",
        "confirm-modal.tsx; confirms built on a plain Modal ×3",
        "move",
        "W3",
      ),
      c(
        "overlays-paged-dialog",
        "PagedDialog",
        ["PagedDialog"],
        "A dialog with a page rail.",
        "as today",
        "paged-dialog.tsx; project-dialogs.tsx:275 hand rail",
        "move",
        "W3",
      ),
      c(
        "overlays-drawer",
        "Drawer",
        ["Drawer", "Sheet"],
        "The side panel and the spring sheet.",
        "as today (Sheet joins the Esc stack)",
        "drawer.tsx, sheet.tsx + lib/spring.ts, lib/sheet-physics.ts",
        "move",
        "W3",
      ),
      c(
        "overlays-floating-panel",
        "FloatingPanel",
        ["FloatingPanel"],
        "The shell every menu, popover and tooltip shares (glass in Frost).",
        "role, width?, className",
        "8 spellings (Select, OptionMenu, InfoPopover, Dropdown, Tooltip, context-gauge.tsx:301, calendar-page.tsx:1107, channel-header.tsx:145)",
        "new",
        "W3",
      ),
      c(
        "overlays-menu",
        "Menu",
        ["Menu", "MenuItem", "MenuSeparator", "MenuLabel", "MenuRadioItem"],
        "One row family at two densities.",
        'MenuItem: {glyph?, label, description?, shortcut?, danger?, checked?, onSelect}; Menu density: "sm" | "md"',
        'menuItemClass, overflowMenuRowClass, menuRowClass, dock add-menu rows, ≈12 hand rows, 5 text "✓"',
        "new",
        "W3",
      ),
      c(
        "overlays-dropdown",
        "Dropdown",
        ["Dropdown"],
        "An anchored panel with a keyboard walk.",
        "as today; in-flow mode kept but deprecated",
        "dropdown.tsx",
        "move",
        "W3",
      ),
      c(
        "overlays-portal-panel",
        "usePortalPanel",
        ["usePortalPanel", "useRowContextMenu"],
        "Positioning and dismissal; three openers.",
        "as today (panelWidth in rem)",
        "use-portal-panel.ts, context-menu.tsx + lib/context-menu.ts",
        "move",
        "W3",
      ),
      c(
        "overlays-info-popover",
        "InfoPopover",
        ["InfoPopover", "HelpFold"],
        'The "?" popover and the help fold.',
        "as today",
        "info-popover.tsx, help-fold.tsx",
        "move",
        "W3",
      ),
      c(
        "overlays-tooltip",
        "Tooltip",
        ["Tooltip"],
        "The tooltip.",
        "as today",
        "tooltip.tsx",
        "move",
        "W3",
      ),
      c(
        "overlays-lightbox",
        "Lightbox",
        ["Lightbox"],
        "A zoomable image.",
        "as today (+ Esc stack)",
        "image-zoom.tsx",
        "move",
        "W3",
      ),
      c(
        "overlays-toaster",
        "Toaster",
        ["Toaster", "toast"],
        "Top toasts on tone tokens.",
        "kinds success | info | attention | error",
        "toast.tsx (KIND_CLASS → tones)",
        "move",
        "W3",
      ),
    ],
  },
  {
    id: "feedback",
    title: "Feedback & Status",
    description: "Badges, counts, notices, skeletons, empty states and progress. Waves W1, W4.",
    sections: [
      c(
        "feedback-badge",
        "Badge",
        ["Badge"],
        "A tone pill: soft, outline or solid.",
        'tone: Tone | "done" | "info", variant?: "soft" | "outline" | "solid", size?: "sm" | "md"',
        "badge.tsx (colour-named tones retired), ≈25 hand pills, model TAG_SHAPE, stopReasonTone",
        "move-new",
        "W1",
      ),
      c(
        "feedback-count",
        "Count",
        ["Count"],
        "A numeric counter pill.",
        "n, max?",
        "section/column/unread counts ×8",
        "new",
        "W1",
      ),
      c(
        "feedback-notice",
        "Notice",
        ["Notice"],
        "The one strip / callout: tone, optional title, action, dismiss and retry.",
        'tone, variant: "strip" | "callout" | "inline", title?, action?: {label,onClick,busy?}, onDismiss?, onRetry?, glyph?',
        "toneStrip frames ×7, ErrorLine ×5 re-spellings, callout-with-action ×6, dismissible hint ×2, login alert",
        "new",
        "W4",
      ),
      c(
        "feedback-todo-notice",
        "TodoNotice",
        ["TodoNotice"],
        "A page to-do, built on Notice.",
        "as today",
        "todo-notice.tsx",
        "move",
        "W4",
      ),
      c(
        "feedback-skeleton",
        "Skeleton",
        ["Skeleton", "SkeletonList", "SkeletonCard"],
        "Loading placeholders.",
        "as today",
        "skeleton.tsx; loading-as-text ×4",
        "move",
        "W1",
      ),
      c(
        "feedback-empty-state",
        "EmptyState",
        ["EmptyState", "SettingsEmpty"],
        "The empty state, optionally dashed.",
        "title, description?, action?, dashed?",
        "empty-state.tsx; ≈55 placeholder lines",
        "move",
        "W1",
      ),
      c(
        "feedback-progress-bar",
        "ProgressBar",
        ["ProgressBar"],
        "Determinate or indeterminate, with tone thresholds.",
        'value, max?, indeterminate?, size?: "xs" | "sm" | "md", tone?, label',
        "BudgetBar, SpendMeter, chart-card.tsx:209, overview-page.tsx:547, update-modal.tsx:270",
        "new",
        "W4",
      ),
      c(
        "feedback-duration-slot",
        "DurationSlot",
        ["DurationSlot", "LiveDuration"],
        "Live elapsed time that settles into a duration.",
        "sinceMs?, durationMs?, running",
        "×7 (thinking-block.tsx:33, work-group.tsx:166, …)",
        "new",
        "W4",
      ),
      c(
        "feedback-beta-badge",
        "BetaBadge",
        ["BetaBadge"],
        "A superscript tag.",
        "label",
        "beta-badge.tsx",
        "move",
        "W4",
      ),
    ],
  },
  {
    id: "layout",
    title: "Layout & Surfaces",
    description: "Cards, page frames, sections, rows and resize handles. Waves W4, W7.",
    sections: [
      c(
        "layout-card",
        "Card",
        ["Card", "CardHeader"],
        "A bordered surface; Frost radius-lg, Console outlined.",
        'padding?: "sm" | "md" | "lg", interactive?, selected?, muted?',
        "10+ card shells (ChartCard, FinanceCard, StatTile, ModelCard, PluginCard, BenchmarkCard, ticket card, login card, …)",
        "new",
        "W4",
      ),
      c(
        "layout-page-frame",
        "PageFrame",
        ["PageFrame", "PageHeader"],
        'The page scroller, width cap, h1 with its "?", and toolbar.',
        "title, info?, actions?, wide?, search?",
        "OrgPage; 9 hand copies (models, agents, plugins, machines, agent-settings, usage, benchmark ×2, company)",
        "lift",
        "W4",
      ),
      c(
        "layout-ruled-section",
        "RuledSection",
        ["RuledSection"],
        'A hairline section: title left, actions right, count and "?".',
        "title, description?, info?, count?, actions?",
        "OrgSection, SectionShell, ×6 border-t pt-4 sections",
        "new",
        "W4",
      ),
      c(
        "layout-collapsible-section",
        "CollapsibleSection",
        ["CollapsibleSection"],
        "A header bar over a collapsing body.",
        "title, actions?, open, onToggle, drag?",
        "models-page.tsx:1144, memory-tab.tsx:586, plugins-page.tsx:494",
        "new",
        "W4",
      ),
      c(
        "layout-disclosure-row",
        "DisclosureRow",
        ["DisclosureRow"],
        "The sticky one-line disclosure.",
        "as today",
        "disclosure-row.tsx; 14 outside shells adopt it in W6",
        "move",
        "W4",
      ),
      c(
        "layout-list-row",
        "ListRow",
        ["ListRow"],
        "A leading tile, title, meta and trailing actions.",
        "lead, title, meta?, trailing?, onTitle?",
        "installed-item row ×2, memory file row, agent row",
        "new",
        "W4",
      ),
      c(
        "layout-entity-header",
        "EntityHeader",
        ["EntityHeader"],
        "Logo or tile, name, id, pills and a link.",
        "icon, name, id?, badges?, link?",
        "models-page.tsx:2961, plugin-detail.tsx:211",
        "new",
        "W4",
      ),
      c(
        "layout-resize-handle",
        "ResizeHandle",
        ["ResizeHandle", "SplitPane"],
        "A pointer drag bar in the info tone.",
        "axis, onResize, min, max",
        "handles ×7 (dock-panel.tsx:849, workspace-browser.tsx:1922, …) + use-pointer-drag.ts",
        "new",
        "W7",
      ),
    ],
  },
  {
    id: "data",
    title: "Data Display",
    description:
      "Tables, key-value lists, stats, logs, legends, rings and sparklines. Waves W4, W8.",
    sections: [
      c(
        "data-table",
        "Table",
        ["Table", "Table.Head", "Table.Row", "Table.Cell", "Table.Expand"],
        "One table family: band or plain header, density, hover, expandable rows.",
        'Table {header?: "band" | "plain", density?: "sm" | "md", sticky?}',
        "3 header styles across ≈12 tables (ToolsTab, vault-tab, schedules-tab, mcp-servers-section, benchmark-detail, …)",
        "new",
        "W4",
      ),
      c(
        "data-key-value",
        "KeyValue",
        ["KeyValue"],
        "A <dl> as a grid or as rows.",
        'items[{label,value,mono?}], layout: "grid" | "rows"',
        "<dl> ×2, KV rows ×3",
        "new",
        "W4",
      ),
      c(
        "data-stat-tile",
        "StatTile",
        ["StatTile"],
        "Glyph, label, toned value and detail; tile or strip.",
        'icon?, label, value, tone?, detail?, jump?; variant: "tile" | "strip"',
        "StatTile, KpiCell, SummaryCard, Stat, Metric",
        "move-new",
        "W4",
      ),
      c(
        "data-stat-chip",
        "StatChip",
        ["StatChip"],
        "A glyph with a mono value.",
        "glyph, value, label",
        "×3 (task-stats-line.tsx:60, chat-page.tsx:150, trace-file-view.tsx:148)",
        "new",
        "W4",
      ),
      c(
        "data-log-view",
        "LogView",
        ["LogView"],
        "A mono <pre> box with an optional header and tail.",
        "text, header?, tail?, wrap?, maxHeight?",
        "raw <pre> log boxes ×6 (OutputTail, machines job log, codeBlock, …)",
        "new",
        "W4",
      ),
      c(
        "data-legend",
        "Legend",
        ["Legend"],
        "A swatch list with three swatch shapes.",
        'items[{label,color,shape?: "dot" | "bar" | "line"}]',
        "×7 legends",
        "new",
        "W8",
      ),
      c(
        "data-ring",
        "Ring",
        ["Ring"],
        "A segmented ring gauge with thresholds.",
        "segments[{value,color}], max, size, tone?, label",
        "SpendRing, FinanceGauge, TokenDonut, context ring",
        "new",
        "W8",
      ),
      c(
        "data-sparkline",
        "Sparkline",
        ["Sparkline"],
        "A polyline with an optional area.",
        "values, area?, width, height, label",
        "score-sparkline.tsx, activity-sparkline.tsx",
        "new",
        "W8",
      ),
      c(
        "data-chart-frame",
        "ChartFrame",
        ["ChartFrame", "chart-geom.ts"],
        "The axes, grid and hover frame.",
        "as today",
        "chart-svg.tsx",
        "move",
        "W8",
      ),
    ],
  },
  {
    id: "content",
    title: "Content",
    description: "Markdown, code, typographic primitives and diffs. Wave W5.",
    sections: [
      c(
        "content-prose",
        "Prose",
        ["Prose", "Md"],
        "react-markdown with the app's plugins and the .md-body CSS.",
        'text, streaming?, variant?: "body" | "compact" | "flush", components?',
        "md.tsx + .md-body* CSS; second renderer in workspace-browser.tsx:2191; .md-body wrapper at 4+ sites",
        "move",
        "W5",
      ),
      c(
        "content-code-block",
        "CodeBlock",
        ["CodeBlock", "CodeSurface"],
        "A language header with copy over a Shiki dual-theme surface.",
        "as today; Shiki theme pair per theme via --ui-code-*",
        "code-block.tsx, highlighter-core.ts, .code-* CSS",
        "move",
        "W5",
      ),
      c(
        "content-typography",
        "Heading & Text",
        ["InlineCode", "Heading", "Text"],
        "Typographic primitives reading the role tokens.",
        'Heading {level: 1-6, as?}; Text {variant: "body" | "small" | "caption" | "eyebrow" | "mono" | "label"}',
        "de-facto scale rows (hero text-3xl, page title text-xl, micro-title text-[11px] uppercase ×9, field label, hint)",
        "new",
        "W5",
      ),
      c(
        "content-diff-viewer",
        "DiffViewer",
        ["DiffViewer"],
        "Unified or split diff with Shiki, hunk headers and word highlights.",
        'before, after | patch, language, mode: "unified" | "split", wrap?',
        "",
        "new",
        "W5",
      ),
      c(
        "content-workspace-file-editor",
        "WorkspaceFileEditor",
        ["WorkspaceFileEditor"],
        "A CodeSurface with a textarea overlay.",
        "as today",
        "workspace-editor.tsx",
        "move",
        "W7",
      ),
    ],
  },
  {
    id: "chat",
    title: "Chat",
    description: "Bubbles, streaming text, tool calls, approvals and the composer. Wave W6.",
    sections: [
      c(
        "chat-message-bubble",
        "MessageBubble",
        ["MessageBubble"],
        "The user, image and steering bubble with hover meta.",
        'align, variant: "text" | "image" | "steer", meta?: {time, copyText}',
        "user bubble chrome ×4 (message-item.tsx:234/262/349/307), MessageMeta",
        "lift",
        "W6",
      ),
      c(
        "chat-assistant-text",
        "AssistantText",
        ["AssistantText", "StreamingCaret"],
        "Settled prose, or streaming text with a caret (Console: a stepped block caret).",
        "text, streaming, stopReason?",
        "message-item.tsx assistant branch",
        "lift",
        "W6",
      ),
      c(
        "chat-work-group",
        "WorkGroup",
        ["WorkGroup", "ThinkingBlock", "StepBanner"],
        "Disclosure cards around steps.",
        "the inventory's props",
        "work-group.tsx, thinking-block.tsx, step-banner.tsx",
        "lift",
        "W6",
      ),
      c(
        "chat-tool-call-card",
        "ToolCallCard",
        ["ToolCallCard"],
        "The tool row: status, name, subtitle, duration, approval, args and output.",
        "displayName, subtitle?, state, durationMs?, pending?: {payload, onDecide}, args?, output?, images?, onSendToBackground?, subagent?",
        "tool-call-card.tsx (toolAliases resolved by web)",
        "lift",
        "W6",
      ),
      c(
        "chat-approval",
        "ApprovalBlock",
        ["ApprovalButtons", "ApprovalBlock"],
        "The allow / deny pair and the attention payload surface.",
        "as today",
        "approval-buttons.tsx, tool-call-card.tsx:520",
        "move",
        "W6",
      ),
      c(
        "chat-subagent-chip",
        "SubagentChip",
        ["SubagentChip"],
        "Avatar, name, id and a spinner or dot.",
        "label, shortId, avatarId, running, pending, onClick",
        "subagent-chip.tsx",
        "lift",
        "W6",
      ),
      c(
        "chat-task-stats-line",
        "TaskStatsLine",
        ["TaskStatsLine"],
        "The per-turn footer chips.",
        "stats, cost?, onFork?, labels",
        "task-stats-line.tsx (uses StatChip)",
        "lift",
        "W6",
      ),
      c(
        "chat-changes-card",
        "ChangesCard",
        ["ChangesCard"],
        '"N files / N memory updates" with show-more.',
        "title, rows[{lead,label,trailing?,onOpen?}], max?: 3",
        "message-files-card.tsx ≡ memory-changes-card.tsx",
        "new",
        "W6",
      ),
      c(
        "chat-context-ring",
        "ContextRing",
        ["ContextRing"],
        "A 14 px ring with 80 / 95 % thresholds.",
        "now, window, unknown?",
        "context-gauge.tsx:234 (the panel stays in web)",
        "lift",
        "W6",
      ),
      c(
        "chat-composer",
        "Composer",
        ["ComposerCard", "ChipRow", "ToolbarTrigger", "SendButton", "SlashMenu"],
        "The composer's shell, chip row, toolbar triggers, send / stop and slash list.",
        'ToolbarTrigger {glyph, label, caret?: "up" | "down"}; SendButton {state: "idle" | "running" | "disabled"}',
        "chat-input.tsx shell pieces; toolbar trigger ×4; send painted bg-gray-900",
        "lift",
        "W6",
      ),
      c(
        "chat-model-select",
        "ModelSelect",
        ["ModelSelect", "ModelMenuList"],
        "The model picker, pill and form variants.",
        "models, value, defaultModel, onChange, variant, labels",
        "model-select.tsx",
        "lift",
        "W6",
      ),
      c(
        "chat-menu-select",
        "MenuSelect",
        ["MenuSelect"],
        "The icon-row select behind the Approval, Thinking, Skill and Agent pickers.",
        "options[{value,glyph?,label,description?}], value, onChange, direction, title?, footer?",
        "chat-input.tsx:161/342/496, draft-view.tsx:978",
        "new",
        "W6",
      ),
      c(
        "chat-channel-bubble",
        "ChannelBubble",
        ["ChannelBubble"],
        "The company group-chat bubble.",
        "own, sender, time, children",
        "channel-view.tsx runs, .channel-bubble CSS",
        "lift",
        "W6",
      ),
    ],
  },
  {
    id: "files",
    title: "Files & Trees",
    description: "The file tree, browser, preview and drop overlay. Wave W7.",
    sections: [
      c(
        "files-file-tree",
        "FileTree",
        ["FileTree"],
        "The workspace file tree.",
        "as today",
        "file-tree.tsx + lib/file-tree.ts",
        "move",
        "W7",
      ),
      c(
        "files-file-browser",
        "FileBrowser",
        ["FileBrowser"],
        "Tree and preview side by side.",
        "as today",
        "file-browser.tsx",
        "move",
        "W7",
      ),
      c(
        "files-tree-pane",
        "TreePane",
        ["TreePane"],
        "The tree with its search, refresh and upload header.",
        "",
        "workspace-browser.tsx",
        "lift",
        "W7",
      ),
      c(
        "files-preview-pane",
        "PreviewPane",
        ["PreviewPane"],
        "Image, PDF, Markdown, source and unsupported previews.",
        "",
        "workspace-browser.tsx",
        "lift",
        "W7",
      ),
      c(
        "files-drop-overlay",
        "DropOverlay",
        ["DropOverlay"],
        "The drag-and-drop target overlay.",
        "",
        "drop-zone.tsx:138 ≡ workspace-browser.tsx:2558",
        "new",
        "W7",
      ),
      c(
        "files-workspace-file-menu",
        "WorkspaceFileMenuRows",
        ["WorkspaceFileMenuRows"],
        "The file context-menu rows.",
        "labels via props",
        "workspace-file-menu.tsx",
        "move",
        "W7",
      ),
    ],
  },
  {
    id: "shell",
    title: "Shell & Dock",
    description: "The app shell, sidebar, dock, launcher and toolbars. Wave W7.",
    sections: [
      c(
        "shell-app-shell",
        "AppShell",
        ["AppShell"],
        "Slots for rail, sidebar, banner, main, dock and drawer.",
        "rail, sidebar, banner, main, dock, drawer",
        "app-layout.tsx",
        "lift",
        "W7",
      ),
      c(
        "shell-sidebar",
        "SidebarFrame",
        ["SidebarFrame", "SessionRow"],
        "The sidebar frame and the presentational session row.",
        "SessionRow: title, time, marks, hover actions, drag",
        "sidebar.tsx",
        "lift",
        "W7",
      ),
      c(
        "shell-dock-frame",
        "DockFrame",
        ["DockFrame"],
        "Header grip, DockTabs, actions, body and ResizeHandle.",
        "",
        "dock-panel.tsx",
        "lift",
        "W7",
      ),
      c(
        "shell-dock-picker",
        "DockPicker",
        ["DockPicker"],
        "The dock's panel picker.",
        "choices via props",
        "dock-panel.tsx",
        "lift",
        "W7",
      ),
      c(
        "shell-launcher",
        "LauncherBall",
        ["LauncherBall", "LauncherFan"],
        "The floating launcher and its fan (springs travel).",
        "",
        "dock-launcher.tsx",
        "lift",
        "W7",
      ),
      c(
        "shell-panels-toolbar",
        "PanelsToolbar",
        ["PanelsToolbar"],
        "The two-toggle panels toolbar.",
        "",
        "panels-toolbar.tsx",
        "lift",
        "W7",
      ),
      c(
        "shell-mobile-top-bar",
        "MobileTopBar",
        ["MobileTopBar"],
        "The mobile top bar.",
        "",
        "app-layout.tsx",
        "lift",
        "W7",
      ),
      c(
        "shell-terminal-appearance",
        "readTerminalAppearance()",
        ["readTerminalAppearance"],
        "The xterm theme and font from the live tokens.",
        "() → { theme: ITheme, fontFamily }",
        "terminal theme literals",
        "new",
        "W7",
      ),
    ],
  },
  {
    id: "charts",
    title: "Charts & Gauges",
    description: "Domain charts stay in web and read --ui-chart-*. Wave W8.",
    sections: [
      c(
        "charts-domain",
        "Domain charts",
        ["TrendChart", "RequestsChart", "TokenBarChart", "ScoreTrendChart", "TimelineChart"],
        "Charts, calendar, kanban and org canvas stay in web, built on ChartFrame, Legend, Ring, Sparkline and ProgressBar.",
        "read --ui-chart-* through the bridge classes",
        "chart inks → --ui-chart-*",
        "lift",
        "W8",
      ),
    ],
  },
  {
    id: "screens",
    title: "Screens",
    description: "Full-viewport composites built from package components and fixtures only.",
    sections: [
      {
        kind: "screen",
        id: "screens-chat",
        screen: "chat",
        title: "Chat",
        description:
          "Sidebar and chat: a running tool call, a thinking block, a settled answer and the composer.",
      },
      {
        kind: "screen",
        id: "screens-traces",
        screen: "traces",
        title: "Traces",
        description: "The Trace panel with its timeline lanes.",
      },
      {
        kind: "screen",
        id: "screens-settings",
        screen: "settings",
        title: "Settings",
        description: "The paged settings dialog open on Appearance.",
      },
      {
        kind: "screen",
        id: "screens-login",
        screen: "login",
        title: "Login",
        description: "The sign-in page.",
      },
    ],
  },
];

/** Every section in render order, with its group. */
export const CATALOG_SECTIONS: readonly { group: CatalogGroup; section: CatalogSection }[] =
  CATALOG.flatMap((group) => group.sections.map((section) => ({ group, section })));
